In [1]:
import pandas as pd
import seaborn as sns
import datetime
import warnings
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('crude_rate.csv')

In [3]:
df = df.replace('Suppressed', 0)

In [4]:
# convert the obj to numeric
df['Deaths'] = pd.to_numeric(df['Deaths'])

In [19]:
df_try = df.groupby('State')

In [21]:
df_try.head()

,State,Year,Deaths,Population,Crude Rate,Crude Rate Lower 95% Confidence Interval,Crude Rate Upper 95% Confidence Interval,Prescriptions Dispensed by US Retailers in that year (millions)
0,Alabama,1999,39,4430141,0.9,0.6,1.2,116
1,Alabama,2000,46,4447100,1,0.8,1.4,126
2,Alabama,2001,67,4467634,1.5,1.2,1.9,138
3,Alabama,2002,75,4480089,1.7,1.3,2.1,142
4,Alabama,2003,54,4503491,1.2,0.9,1.6,149
16,Alaska,1999,28,624779,4.5,3,6.5,116
17,Alaska,2000,27,626932,4.3,2.8,6.3,126
18,Alaska,2001,17,633714,Unreliable,1.6,4.3,138
19,Alaska,2002,0,642337,0,0,0,142
20,Alaska,2003,14,648414,Unreliable,1.2,3.6,149
32,Arizona,1999,250,5023823,5,4.4,5.6,116
33,Arizona,2000,249,5130632,4.9,4.3,5.5,126
34,Arizona,2001,275,5273477,5.2,4.6,5.8,138
35,Arizona,2002,340,5396255,6.3,5.6,7,142
36,Arizona,2003,350,5510364,6.4,5.7,7,149
48,Arkansas,1999,29,2651860,1.1,0.7,1.6,116
49,Arkansas,2000,20,2673400,0.7,0.5,1.2,126
50,Arkansas,2001,30,2691571,1.1,0.8,1.6,138
51,Arkansas,2002,96,2705927,3.5,2.9,4.3,142
52,Arkansas,2003,98,2724816,3.6,2.9,4.4,149
64,California,1999,1598,33499204,4.8,4.5,5,116
65,California,2000,1105,33871648,3.3,3.1,3.5,126
66,California,2001,605,34479458,1.8,1.6,1.9,138
67,California,2002,1583,34871843,4.5,4.3,4.8,142
68,California,2003,1530,35253159,4.3,4.1,4.6,149
80,Colorado,1999,169,4226018,4,3.4,4.6,116
81,Colorado,2000,184,4301261,4.3,3.7,4.9,126
82,Colorado,2001,204,4425687,4.6,4,5.2,138
83,Colorado,2002,206,4490406,4.6,4,5.2,142
84,Colorado,2003,229,4528732,5.1,4.4,5.7,149
...,...,...,...,...,...,...,...,...
720,Vermont,1999,17,604683,Unreliable,1.6,4.5,116
721,Vermont,2000,24,608827,3.9,2.5,5.9,126
722,Vermont,2001,39,612223,6.4,4.5,8.7,138
723,Vermont,2002,41,615442,6.7,4.8,9,142
724,Vermont,2003,50,617858,8.1,6,10.7,149
736,Virginia,1999,210,7000174,3,2.6,3.4,116
737,Virginia,2000,260,7078515,3.7,3.2,4.1,126
738,Virginia,2001,326,7198362,4.5,4,5,138
739,Virginia,2002,361,7286873,5,4.4,5.5,142
740,Virginia,2003,374,7366977,5.1,4.6,5.6,149
752,Washington,1999,372,5842564,6.4,5.7,7,116
753,Washington,2000,374,5894121,6.3,5.7,7,126
754,Washington,2001,332,5985722,5.5,4.9,6.1,138
755,Washington,2002,474,6052349,7.8,7.1,8.5,142
756,Washington,2003,492,6104115,8.1,7.3,8.8,149
768,West Virginia,1999,34,1811799,1.9,1.3,2.6,116
769,West Virginia,2000,52,1808344,2.9,2.1,3.8,126
770,West Virginia,2001,150,1801481,8.3,7,9.7,138
771,West Virginia,2002,183,1805414,10.1,8.7,11.6,142
772,West Virginia,2003,203,1812295,11.2,9.7,12.7,149
784,Wisconsin,1999,85,5332666,1.6,1.3,2,116
785,Wisconsin,2000,117,5363675,2.2,1.8,2.6,126
786,Wisconsin,2001,143,5406835,2.6,2.2,3.1,138
787,Wisconsin,2002,173,5445162,3.2,2.7,3.7,142
788,Wisconsin,2003,203,5479203,3.7,3.2,4.2,149
800,Wyoming,1999,0,491780,0,0,0,116
801,Wyoming,2000,10,493782,Unreliable,1,3.7,126
802,Wyoming,2001,0,494657,0,0,0,138
803,Wyoming,2002,17,500017,Unreliable,2,5.4,142
804,Wyoming,2003,0,503453,0,0,0,149

In [5]:
df.columns

Index(['State', 'Year', 'Deaths', 'Population', 'Crude Rate',
       'Crude Rate Lower 95% Confidence Interval',
       'Crude Rate Upper 95% Confidence Interval',
       'Prescriptions Dispensed by US Retailers in that year (millions)'],
      dtype='object')

In [6]:
# Functions
def subseting (df):
    df_copy = df.copy()
    df_copy= df[df.State == 'Alaska']
    df_copy = df_copy[[ 'Year' , 'Deaths']]
    return df_copy

def convert_to_dt(row):
    dt = datetime.datetime(row.Year, 1, 1)
    return dt

In [16]:
def sisi (df , rows):
    df_copy = df.copy()
    for i in rows:
        df_copy = df.loc[df["State"] == i, ["Year", "Deaths"]]
    return df_copy

In [18]:
a = df.State.unique()
b = [ 'Alaska', "Alabama"]
# for i in a:
#     print(sisi(df ,i))
print(sisi(df, b))


# subsets = subsetting2(df, ["Alaska", "Alabama"])
# for s in subsets:
#     print(s)

    Year  Deaths
0   1999      39
1   2000      46
2   2001      67
3   2002      75
4   2003      54
5   2004      92
6   2005      83
7   2006     134
8   2007     172
9   2008     195
10  2009     210
11  2010     194
12  2011     180
13  2012     175
14  2013     175
15  2014     282

In [19]:
df.loc[df["State"] == 'Alabama', ["Year", "Deaths"]]

    Year  Deaths
0   1999      39
1   2000      46
2   2001      67
3   2002      75
4   2003      54
5   2004      92
6   2005      83
7   2006     134
8   2007     172
9   2008     195
10  2009     210
11  2010     194
12  2011     180
13  2012     175
14  2013     175
15  2014     282

In [13]:
def subseting_33 (df ,list_of_states):
    df_copy = df.copy()
    for i in list_of_states:
        df_copy = df[df['State'].isin(['i'])]
        df_copy = df[[ 'Year' , 'Deaths']]
    return df_copy

In [20]:
a = ['Alaska', 'Alabama']
subseting_33(df , a)

     Year  Deaths
0    1999      39
1    2000      46
2    2001      67
3    2002      75
4    2003      54
5    2004      92
6    2005      83
7    2006     134
8    2007     172
9    2008     195
10   2009     210
11   2010     194
12   2011     180
13   2012     175
14   2013     175
15   2014     282
16   1999      28
17   2000      27
18   2001      17
19   2002       0
20   2003      14
21   2004      11
22   2005      19
23   2006      29
24   2007      16
25   2008      94
26   2009      94
27   2010      71
28   2011      72
29   2012      81
..    ...     ...
786  2001     143
787  2002     173
788  2003     203
789  2004     226
790  2005     281
791  2006     352
792  2007     390
793  2008     380
794  2009     406
795  2010     420
796  2011     484
797  2012     496
798  2013     604
799  2014     640
800  1999       0
801  2000      10
802  2001       0
803  2002      17
804  2003       0
805  2004      14
806  2005      10
807  2006      14
808  2007      25
809  2008      48
810  2009      34
811  2010      49
812  2011      47
813  2012      47
814  2013      52
815  2014      57

[816 rows x 2 columns]